### ISSUE TITLE
2022 Update

### ISSUE THREAD

**Issue by AlexFielder** [koechlm/VDS-Configuration-Editor#1]
Hi there,

Is it possible for you to update this to function with Vault 2022 please?

Regards,

Alex.

**Comment by koechlm** [comment]
Hi Alex, it is up to date: switch to the 2022 branch and download from there: https://github.com/koechlm/VDS-Configuration-Editor/tree/2022
Hope this helps,
Markus

**Comment by AlexFielder** [comment]
That's great Markus, thank you. :)
