### ISSUE TITLE
Links are lost if the project is not cloned into C: drive

### ISSUE THREAD

**Issue by smilinger** [koechlm/VDS-Configuration-Editor#2]
If the project is cloned into D: drive, the links to the configuration files would point to "D:\ProgramData\...", links are lost.
Please consider changing the path in the project file from relative paths to absolute paths.

**Comment by koechlm** [comment]
I am aware, but the effort to switch from relative to absolute is more than nasty if you work dynamically adding new configurations or additional configuration files. However, the project covering the default configuration should be changed at least!
